language: node_js
node_js:
 - "6"

before_install:
 - npm install -g grunt-cli

script:
 - grunt test

notifications:
  email:
    recipients:
      - edwingamboa355@gmail.com
    on_success: change
    on_failure: always
